---
title: "omarpineda_chapter8"
author: "Omar Pineda"
date: "5/5/2019"
output: html_document
---

8.2, 8.4, 8.8, 8.16, 8.18

8.2 Baby weights, Part II. Exercise 8.1 introduces a data set on birth weight of babies.
Another variable we consider is parity, which is 0 if the child is the first born, and 1 otherwise.
The summary table below shows the results of a linear regression model for predicting the average
birth weight of babies, measured in ounces, from parity.

(a) Write the equation of the regression line.
Y = 120.07−1.93(parity)

(b) Interpret the slope in this context, and calculate the predicted birth weight of first borns and
others.

First borns have birth weights that are 1.93 ounces higher than others.

Others: 120.07 - 1.93 * 1 = 118.14

First born: 120.07 - 1.93 * 0 = 120.07

(c) Is there a statistically significant relationship between the average birth weight and parity?

With p-value = 0.1 > 0.05, we fail to reject the null hypothesis and conclude that there is no significant difference between average birth weight and parity.

8.4 Absenteeism. Researchers interested in the relationship between absenteeism from school
and certain demographic characteristics of children collected data from 146 randomly sampled students in rural New South Wales, Australia, in a particular school year. Below are three observations
from this data set.

The summary table below shows the results of a linear regression model for predicting the average
number of days absent based on ethnic background (eth: 0 - aboriginal, 1 - not aboriginal), sex
(sex: 0 - female, 1 - male), and learner status (lrn: 0 - average learner, 1 - slow learner).

(a) Write the equation of the regression line.

Y = 18.93−9.11(eth)+3.10(sex)+2.15(lrn)

(b) Interpret each one of the slopes in this context.

eth: number of absent days is 9.11 days lower for aboriginal students
sex: number of absent days is 3.10 days higher for female students
lrn: number of absent days is 2.15 days higher for slower learners than average learners

(c) Calculate the residual for the first observation in the data set: a student who is aboriginal,
male, a slow learner, and missed 2 days of school.

The number of absent days from the model is 24.18 while the observed value is 2. The residual is thus -22.18.

(d) The variance of the residuals is 240.57, and the variance of the number of absent days for all
students in the data set is 264.17. Calculate the R2 and the adjusted R2. Note that there are
146 observations in the data set.

R^2 = 1 - (240.57/264.17) = 0.0893
Adjusted R^2 = 1 - (240.57/264.17) * [(146-1)/(146-3-1)] = 0.0701

8.8 Absenteeism, Part II. Exercise 8.4 considers a model that predicts the number of days
absent using three predictors: ethnic background (eth), gender (sex), and learner status (lrn).
The table below shows the adjusted R-squared for the model as well as adjusted R-squared values
for all models we evaluate in the first step of the backwards elimination process.

Which, if any, variable should be removed from the model first?

The model with no learner status should be removed first as it yields a higher adjusted R^2 value than our adjusted R^2 value with all of the explanatory variables.

8.16 Challenger disaster, Part I. On January 28, 1986, a routine launch was anticipated for
the Challenger space shuttle. Seventy-three seconds into the flight, disaster happened: the shuttle
broke apart, killing all seven crew members on board. An investigation into the cause of the
disaster focused on a critical seal called an O-ring, and it is believed that damage to these O-rings
during a shuttle launch may be related to the ambient temperature during the launch. The table
below summarizes observational data on O-rings for 23 shuttle missions, where the mission order
is based on the temperature at the time of the launch. Temp gives the temperature in Fahrenheit,
Damaged represents the number of damaged O-rings, and Undamaged represents the number of
O-rings that were not damaged.

(a) Each column of the table above represents a di↵erent shuttle mission. Examine these data
and describe what you observe with respect to the relationship between temperatures and
damaged O-rings.

All but 1 out of 23 missions had either no damaged O-rings or just 1 damaged O-ring. The mission with the most damaged O-rings launched on the coldest day. All missions launched in temperature below 65 F had at least one damaged O-ring. There may a relationship between these two variables. 

(b) Failures have been coded as 1 for a damaged O-ring and 0 for an undamaged O-ring, and
a logistic regression model was fit to these data. A summary of this model is given below.
Describe the key components of this summary table in words.

There is a negative relationship between temperature and O-ring failures. With a p−value < 0.05, the relationship between temperature and O-ring failure is significant.

(c) Write out the logistic model using the point estimates of the model parameters.

log(p/(1-p)) = 11.6630−0.2162(Temperature)

(d) Based on the model, do you think concerns regarding O-rings are justified? Explain.

Yes, concerns are justified as the relationship between 0-ring failures and temperature is significant.

8.18 Challenger disaster, Part II. Exercise 8.16 introduced us to O-rings that were identified
as a plausible explanation for the breakup of the Challenger space shuttle 73 seconds into takeo↵
in 1986. The investigation found that the ambient temperature at the time of the shuttle launch
was closely related to the damage of O-rings, which are a critical component of the shuttle. See
this earlier exercise if you would like to browse the original data.

(a) The data provided in the previous exercise are shown in the plot. The logistic model fit to
these data may be written as

(a) The data provided in the previous exercise are shown in the plot. The logistic model fit to
these data may be written as

log(p/(1-p)) = 11.6630 - 0.2162 (Temperature)

where p is the model-estimated probability that an O-ring will become damaged. Use the
model to calculate the probability that an O-ring will become damaged at each of the following
ambient temperatures: 51, 53, and 55 degrees Fahrenheit.

Solving for p in the above equation, we have:

p = 65.36% when temparature = 51

p = 55.05% when temparature = 53

p = 44.28% when temparature = 55

(b) Add the model-estimated probabilities from part (a) on the plot, then connect these dots using
a smooth curve to represent the model-estimated probabilities.

```{r probabilities}
library(ggplot2)
probs <- data.frame(pbs = c(.654, .551, .443, .341, .251, .179, .124, .084, .056, .037, .024), index = c(1:11))
ggplot(probs) + geom_smooth(aes(y = pbs, x = index))
```
(c) Describe any concerns you may have regarding applying logistic regression in this application,
and note any assumptions that are required to accept the model’s validity.

We assume that observations are independent but they may not be if the rings are manufactured by the same company. We are looking at damage as either damaged or not damaged but there are actually levels to the amount of damage that we observe. The sample size may also not be large enough.